#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1475819970                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Libi                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your personal libido and mood tracker.<br>Soon on the iOS App Store.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Daniel aka breakthesystem
your_link                                 : http://breakthesystem.org
your_city                                 : Augsburg
email_address                             : libi@breakthesystem.org
facebook_username                         :                                           
instagram_username                        : libitracker
twitter_username                          : libitracker
github_username                           : winsmith
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Track your libido, mood, and sexual activity
    description                           : Be more aware of how your body works, and how stress, workouts, and other factors influence your libidinal cycle. Find out short- and long-term trends and improve your mental health and/as well as your awareness of your needs and wants. 
    fontawesome_icon_name                 : magic

  - title                                 : Track your Menstrual Cycle
    description                           : If you menstruate, you can also quickly and easily enter menstrual flow, learn more about your cycle’s influence on your life, and use Apple Health algorithms to analyze and predict your cycle.
    fontawesome_icon_name                 : smile-beam
    
  - title                                 : Find Connections
    description                           : Once you’ve started tracking your mood, libido, sexual activity and menstrual flow, you will discover beautiful charts that can give you a quick and glanceable idea of how you’re doing, where you’re going and historical trends.
    fontawesome_icon_name                 : chart-line

  - title                                 : Private by Design
    description                           : Libi takes great care of your data. There are no accounts and no custom syncing, just iCloud and Apple Health. Your data stays on your devices! <a href="./privacypolicy">Privacy Policy</a>
    fontawesome_icon_name                 : lock

  - title                                 : Quick and easy entry
    description                           : Entering data is just one swipe in Libi’s attractive and streamlined user interface (which supports Dark Mode of course).
    fontawesome_icon_name                 : lock

  - title                                 : Sync with Health App
    description                           : Libi will read and write all compatible data types directly from and into the Apple Health App on your phone using HealthKit. 
    fontawesome_icon_name                 : lock



# Theme Settings
topbar_color                              : "#1C0658"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#36CDC4"
cover_overlay_transparency                : 0.8

device_color                              : yellow                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#5C2686"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#1C0658"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#5C2686"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
